# Quiz 3

------------------------------------------------------------------------

## Pregunta 1

Use los datos siguientes para la primera pregunta

Aqui se encuentra un grupo de datos de la distancia a estrellas en años luz.

```{r, eval=FALSE}
library(tidyverse)
Distancia_Estrellas=tribble(~Distancia,
  8.6,36.7,42.2,16.8,33.7,87.9,4.4,25.3,11.4,25.1,51.5
)

Distancia_Estrellas
```

```{r}
sd(
Distancia_Estrellas$Distancia)
```




```{r, echo=FALSE, eval=FALSE}
library(readr)
estimados_anuales_poblacionales_por_municipio_y_pr_annual_population_estimates_for_pr_and_its_m <- read_csv("Data_files_csv/estimados_anuales_poblacionales_por_municipio_y_pr_annual_population_estimates_for_pr_and_its_m.csv")
muni=estimados_anuales_poblacionales_por_municipio_y_pr_annual_population_estimates_for_pr_and_its_m

muni
```

```{r, echo=FALSE, eval=FALSE}



Muni_all=muni %>% 
  pivot_longer(cols=Adjuntas:Yauco,
     names_to = "Municipality", 
     values_to = "Pop_N")

Muni_2022=Muni_all %>% dplyr::select(Año, Municipality, Pop_N) %>% 
  filter(Año ==2022)

Muni_2022

write_csv(Muni_2022, "Muni_2022.csv")
```

------------------------------------------------------------------------

## Pregunta 2

Use los siguientes datos para la segunda pregunta

```{r}


Pop_PR_2022 = tribble(
~Anio,	~Municipality,	~Pop_N,
2022,	"Adjuntas",	17905,
2022,	"Aguada",	37666,
2022,	"Aguadilla",	53931,
2022,	"Aguas Buenas",	23538,
2022,	"Aibonito",	24555,
2022,	"Anasco",	25026,
2022,	"Arecibo",	86090,
2022,	"Arroyo",	15289,
2022,	"Barceloneta",	22416,
2022,	"Barranquitas",	28944,
2022,	"Bayamon",	181577,
2022,	"Cabo Rojo",	46718,
2022,	"Caguas",	125136,
2022,	"Camuy",	32620,
2022,	"Canovanas",	41637,
2022,	"Carolina",	151571,
2022,	"Catano",	22364,
2022,	"Cayey",	40782,
2022,	"Ceiba",	10931,
2022,	"Ciales",	16742,
2022,	"Cidra",	39515,
2022,	"Coamo",	33887,
2022,	"Comerio",	18619,
2022,	"Corozal",	34322,
2022,	"Culebra",	1769,
2022,	"Dorado",	35663,
2022,	"Fajardo",	31375,
2022,	"Florida",	11538,
2022,	"Guanica",	12800,
2022,	"Guayama",	35262,
2022,	"Guayanilla",	17064,
2022,	"Guaynabo",	89057,
2022,	"Gurabo",	40061,
2022,	"Hatillo",	38021,
2022,	"Hormigueros",	15413,
2022,	"Humacao",	49924,
2022,	"Isabela",	42754,
2022,	"Jayuya",	14495,
2022,	"Juana Diaz",	45923,
2022,	"Juncos",	36672,
2022,	"Lajas",	22936,
2022,	"Lares",	27774,
2022,	"Las Marias",	8705,
2022,	"Las Piedras",	34814,
2022,	"Loiza",	22657,
2022,	"Luquillo",	17449,
2022,	"Manati",	38751,
2022,	"Maricao",	4575,
2022,	"Maunabo",	10368,
2022,	"Mayaguez",	70609,
2022,	"Moca",	37279,
2022,	"Morovis",	28277,
2022,	"Naguabo",	22964,
2022,	"Naranjito",	29208,
2022,	"Orocovis",	21229,
2022,	"Patillas",	15524,
2022,	"Penuelas",	19763,
2022,	"Ponce",	132138,
2022,	"Quebradillas",	23332,
2022,	"Rincon",	15316,
2022,	"Rio Grande",	45840,
2022,	"Sabana Grande",	22351,
2022,	"Salinas",	25000,
2022,	"San German",	31174,
2022,	"San Juan",	334776,
2022,	"San Lorenzo",	37260,
2022,	"San Sebastian",	38969,
2022,	"Santa Isabel",	19822,
2022,	"Toa Alta",	66041,
2022,	"Toa Baja",	72783,
2022,	"Trujillo Alto",	66810,
2022,	"Utuado",	27535,
2022,	"Vega Alta",	34786,
2022,	"Vega Baja",	53684,
2022,	"Vieques",	8043,
2022,	"Villalba",	21466,
2022,	"Yabucoa",	29305,
2022,	"Yauco",	32904,
)

Pop_PR_2022
```

## Calcular el quantile 50
```{r, echo=FALSE, eval=FALSE}

quantile(Muni_2022$Pop_N, p=c(0.01, 0.10, .25, .50, .75, 0.99))
median(Muni_2022$Pop_N)
mean(Muni_2022$Pop_N)
```
***

Calcular el indice de oblicuidad de los datos de los tamaños de población de PR

```{r, echo=FALSE, eval=FALSE}
library(e1071)
e1071::skewness(Muni_2022$Pop_N)
```




```{r, echo=FALSE, eval=FALSE}

ggplot(Muni_2022, aes(Pop_N))+
  geom_histogram()
```

