<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Capítulo 13 Prueba de una Muestra | BioEstadística</title>
<meta name="author" content="">
<meta name="description" content='library(gridExtra) library(tidyverse) Fecha de la última revisión ## [1] "2026-08-01"  13.1 El promedio, un estimado En este módulo se evalúan el promedio y las propiedades de una distribución...'>
<meta name="generator" content="bookdown 0.47 with bs4_book()">
<meta property="og:title" content="Capítulo 13 Prueba de una Muestra | BioEstadística">
<meta property="og:type" content="book">
<meta property="og:description" content='library(gridExtra) library(tidyverse) Fecha de la última revisión ## [1] "2026-08-01"  13.1 El promedio, un estimado En este módulo se evalúan el promedio y las propiedades de una distribución...'>
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Capítulo 13 Prueba de una Muestra | BioEstadística">
<meta name="twitter:description" content='library(gridExtra) library(tidyverse) Fecha de la última revisión ## [1] "2026-08-01"  13.1 El promedio, un estimado En este módulo se evalúan el promedio y las propiedades de una distribución...'>
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Source_Sans_3-0.4.10/font.css" rel="stylesheet">
<link href="libs/Fira_Code-0.4.10/font.css" rel="stylesheet">
<link href="libs/Lora-0.4.10/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.11.0/transition.js"></script><script src="libs/bs3compat-0.11.0/tabs.js"></script><script src="libs/bs3compat-0.11.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link rel="icon" type="image/x-icon" href="favicon.ico">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">BioEstadística</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Introducción al curso de BioEstadística</a></li>
<li><a class="" href="introducci%C3%B3n-a-la-bioestad%C3%ADstica.html"><span class="header-section-number">2</span> Introducción a la BioEstadística</a></li>
<li><a class="" href="poblaci%C3%B3n-y-muestreo.html"><span class="header-section-number">3</span> Población y Muestreo</a></li>
<li><a class="" href="inferencias-e-hip%C3%B3tesis.html"><span class="header-section-number">4</span> Inferencias e Hipótesis</a></li>
<li><a class="" href="historia-breve-de-la-estad%C3%ADstica.html"><span class="header-section-number">5</span> Historia breve de la Estadística</a></li>
<li><a class="" href="medidas-de-tendencia-central.html"><span class="header-section-number">6</span> Medidas de tendencia central</a></li>
<li><a class="" href="medidas-de-dispersi%C3%B3n.html"><span class="header-section-number">7</span> Medidas de dispersión</a></li>
<li><a class="" href="estad%C3%ADstica-descriptiva.html"><span class="header-section-number">8</span> Estadística Descriptiva</a></li>
<li><a class="" href="gr%C3%A1ficos.html"><span class="header-section-number">9</span> Gráficos</a></li>
<li><a class="" href="supuestos.html"><span class="header-section-number">10</span> Supuestos</a></li>
<li><a class="" href="estad%C3%ADstica-frecuentista.html"><span class="header-section-number">11</span> Estadística Frecuentista</a></li>
<li><a class="" href="distribuci%C3%B3n-normal.html"><span class="header-section-number">12</span> Distribución Normal</a></li>
<li><a class="active" href="prueba-de-una-muestra.html"><span class="header-section-number">13</span> Prueba de una Muestra</a></li>
<li><a class="" href="prueba-de-t-para-datos-pareados.html"><span class="header-section-number">14</span> Prueba de t para Datos Pareados</a></li>
<li><a class="" href="prueba-de-t-con-datos-independientes.html"><span class="header-section-number">15</span> Prueba de t con Datos Independientes</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">16</span> ANOVA</a></li>
<li><a class="" href="correlaci%C3%B3n-y-covarianza.html"><span class="header-section-number">17</span> Correlación y Covarianza</a></li>
<li><a class="" href="regresi%C3%B3n-lineal-1.html"><span class="header-section-number">18</span> Regresión Lineal</a></li>
<li><a class="" href="regresi%C3%B3n-log%C3%ADstica.html"><span class="header-section-number">19</span> Regresión Logística</a></li>
<li><a class="" href="selecci%C3%B3n-de-modelos-con-el-criterio-de-akaike.html"><span class="header-section-number">20</span> Selección de Modelos con el Criterio de Akaike</a></li>
<li><a class="" href="pruebas-no-param%C3%A9tricas.html"><span class="header-section-number">21</span> Pruebas No Paramétricas</a></li>
<li><a class="" href="referencias-1.html">Referencias</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="ejercicios-a.html"><span class="header-section-number">A</span> Ejercicios A</a></li>
<li><a class="" href="ejercicios-b.html"><span class="header-section-number">B</span> Ejercicios B</a></li>
<li><a class="" href="ejercicios-c.html"><span class="header-section-number">C</span> Ejercicios C</a></li>
<li><a class="" href="ejercicios-d.html"><span class="header-section-number">D</span> Ejercicios D</a></li>
<li><a class="" href="ejercicios-e.html"><span class="header-section-number">E</span> Ejercicios E</a></li>
<li><a class="" href="ejercicios-f.html"><span class="header-section-number">F</span> Ejercicios F</a></li>
<li><a class="" href="ejercicios-g.html"><span class="header-section-number">G</span> Ejercicios G</a></li>
<li><a class="" href="ejercicios-h.html"><span class="header-section-number">H</span> Ejercicios H</a></li>
<li><a class="" href="ejercicios-i.html"><span class="header-section-number">I</span> Ejercicios I</a></li>
<li><a class="" href="ejercicios-j.html"><span class="header-section-number">J</span> Ejercicios J</a></li>
<li><a class="" href="ejercicios-k.html"><span class="header-section-number">K</span> Ejercicios K</a></li>
<li><a class="" href="ejercicios-l-prueba-de-t-con-datos-independientes.html"><span class="header-section-number">L</span> Ejercicios L: prueba de t con datos independientes</a></li>
<li><a class="" href="ejercicios-m.html"><span class="header-section-number">M</span> Ejercicios M</a></li>
<li><a class="" href="ejercicios-n.html"><span class="header-section-number">N</span> Ejercicios N</a></li>
<li><a class="" href="ejercicio-o.html"><span class="header-section-number">O</span> Ejercicio O</a></li>
<li><a class="" href="ejercicios-p.html"><span class="header-section-number">P</span> Ejercicios P</a></li>
<li><a class="" href="data.html"><span class="header-section-number">Q</span> DATA</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/RaymondLTremblay/BioEstadistica">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="prueba-de-una-muestra" class="section level1" number="13">
<h1>
<span class="header-section-number">Capítulo 13</span> Prueba de una Muestra<a class="anchor" aria-label="anchor" href="#prueba-de-una-muestra"><i class="fas fa-link"></i></a>
</h1>
<div class="sourceCode" id="cb425"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">gridExtra</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div>
<p>Fecha de la última revisión</p>
<pre><code>## [1] "2026-08-01"</code></pre>
<p><img src="Graficos/hex_ggversa.png" alt="" width="20%"><img src="Graficos/hex_error.png" alt="" width="20%"></p>
<hr>
<div id="el-promedio-un-estimado" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> El promedio, un estimado<a class="anchor" aria-label="anchor" href="#el-promedio-un-estimado"><i class="fas fa-link"></i></a>
</h2>
<p>En este módulo se evalúan el promedio y las propiedades de una distribución normal y el muestreo para estimar el promedio. También se evalúa la hipótesis de un muestreo y se estima el intervalo de confianza para el posible rango del promedio. Es importante reconocer que el promedio estimado a partir de un muestreo, <span class="math inline">\(\overline{x}\)</span>, es solamente un estimado. En otras palabras, no es necesariamente la VERDAD, o dicho de forma estadística, el promedio del universo, <span class="math inline">\(\mu\)</span>, de esta variable.</p>
<p>Con frecuencia se quiere conocer información sobre el verdadero promedio, <span class="math inline">\(\mu\)</span>, basado en un muestreo. Por ejemplo, cuál es el promedio de la edad de las Palmas de Sierra en Puerto Rico, cuál es el promedio de la presión arterial de los humanos, o cuál es la producción promedio de mangos en los árboles de mango. En cada caso no sabemos cuál es el promedio universal, <span class="math inline">\(\mu\)</span>, y tampoco sabemos el valor exacto de la desviación estándar, <span class="math inline">\(\sigma\)</span>.</p>
<p>Para evaluar la hipótesis sobre el promedio de la población <span class="math inline">\(\mu\)</span>, uno puede utilizar datos recogidos al azar (un muestreo) y usarlos para inferir cuál es el promedio y la desviación estándar del universo.</p>
</div>
<div id="ejemplo-9.1-y-9.2." class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Ejemplo 9.1 y 9.2.<a class="anchor" aria-label="anchor" href="#ejemplo-9.1-y-9.2."><i class="fas fa-link"></i></a>
</h2>
<p>Lean estos dos ejercicios y consideren cuáles son los valores del universo, <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span>, y el promedio del muestreo, <span class="math inline">\(\overline{x}\)</span>.</p>
</div>
<div id="la-distribución-de-t" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> La distribución de t<a class="anchor" aria-label="anchor" href="#la-distribuci%C3%B3n-de-t"><i class="fas fa-link"></i></a>
</h2>
<p>Cuando queremos inferir información sobre el promedio o la desviación del universo a partir de un muestreo, hay que utilizar la distribución de <em>t</em>. La razón es que la forma de la distribución cambia con el tamaño de muestra cuando no sabemos cuál es la desviación estándar del universo. A medida que uno reduce el tamaño de muestra, la distribución se desvía de una distribución normal. Para tomar esto en cuenta no usamos la distribución normal, sino la distribución de <em>t</em>, también llamada la distribución <em>t</em> de Student.</p>
<div class="sourceCode" id="cb427"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">out</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">df1x</span>, <span class="va">val</span>, colour<span class="op">=</span><span class="va">df</span><span class="op">)</span> <span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="va">rlt_theme</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_colour_manual</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Grado de \nlibertad"</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"blue"</span>, <span class="st">"red"</span>, <span class="st">"springgreen4"</span>, <span class="st">"black"</span><span class="op">)</span>, </span>
<span>                     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">nu</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">nu</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,<span class="va">nu</span><span class="op">[</span><span class="fl">5</span><span class="op">]</span>, <span class="va">nu</span><span class="op">[</span><span class="va">infinity</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>                     <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.8</span>, <span class="fl">0.8</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>                     <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Valores"</span><span class="op">)</span><span class="op">+</span></span>
<span>                     <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Densidad"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="BioEstadistica_files/figure-html/c13-10-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb428"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsave.html">ggsave</a></span><span class="op">(</span><span class="st">"t-distribution.png"</span><span class="op">)</span></span></code></pre></div>
<p>Observa cómo cambia la distribución de <em>t</em> cuando cambia el tamaño de muestra (el grado de libertad es <span class="math inline">\(\nu=n-1\)</span>). Hay que observar dos componentes: 1. hay menos datos centrados en el promedio y 2. hay más datos en las colas.</p>
<p>Se usa la distribución de <em>t</em> para calcular el intervalo de confianza y la hipótesis del promedio de una muestra, debido a que la forma de la distribución de <em>t</em> cambia con el tamaño de muestra (<span class="math inline">\(\nu=n-1\)</span>) y también con la tasa de error Tipo I, <span class="math inline">\(\alpha\)</span>.</p>
<p>La prueba de un muestreo es</p>
<p><span class="math display">\[t=\frac{\overline{x}-\mu}{s/\sqrt{n}}\]</span></p>
<div class="formula">
<p>En la prueba de <em>t</em> de una muestra: <span class="math inline">\(\overline{x}\)</span> es el promedio de la muestra, <span class="math inline">\(\mu\)</span> es el valor propuesto por la hipótesis nula, <span class="math inline">\(s\)</span> es la desviación estándar de la muestra y <span class="math inline">\(n\)</span> es el tamaño de muestra. El denominador <span class="math inline">\(s/\sqrt{n}\)</span> es el <strong>error estándar</strong> del promedio.</p>
</div>
<hr>
</div>
<div id="cuando-es-que-uno-rechaza-la-hipótesis-nula" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Cuando es que uno rechaza la hipótesis nula<a class="anchor" aria-label="anchor" href="#cuando-es-que-uno-rechaza-la-hip%C3%B3tesis-nula"><i class="fas fa-link"></i></a>
</h2>
<p>Regresamos a la idea de Tipo de error I. Cuando se selecciona un <span class="math inline">\(\alpha=0.05\)</span>, lo que estamos diciendo es que hay un 5% de probabilidad de cometer un error Tipo I, que es <span style="color: blue;">rechazar la hipótesis nula cuando en realidad es verdadera</span>. Este 5% se puede dividir en dos componentes, uno cuando el valor es más pequeño y otro cuando es más grande que el valor esperado. Por consiguiente, el área de rechazo de la hipótesis nula es 0.025 en la parte negativa y 0.025 en la positiva.</p>
<p>Seleccionamos la curva con un grado de libertad de 5 y evaluamos el área de la curva que está dentro del 95% del intervalo de confianza y la que queda fuera de este rango. Si el promedio estimado de una prueba de <em>t</em> cae dentro del área en gris, no se rechaza la hipótesis nula; si cae en el área roja, se rechaza la hipótesis nula. Nota que para esta hipótesis hay dos maneras de rechazar la hipótesis nula (por ambos extremos).</p>
<div class="sourceCode" id="cb429"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">d6</span> <span class="op">&lt;-</span> <span class="va">d5</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_area</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">db5</span>, <span class="va">x</span> <span class="op">&gt;</span> <span class="va">rand5</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"red"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_area</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">db5</span>, <span class="va">x</span> <span class="op">&lt;</span> <span class="op">-</span><span class="va">rand5</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"red"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="va">rlt_theme</span></span>
<span><span class="va">d6</span></span></code></pre></div>
<div class="inline-figure"><img src="BioEstadistica_files/figure-html/c13-12-1.png" alt="" width="672"></div>
<hr>
<p>La alternativa es que nuestra hipótesis sea de un solo lado, donde el total del 5% está en la parte inferior o en la superior. En este caso se rechaza solamente si el valor se encuentra en esa proporción de los valores de <em>t</em>. Nota ahora que el área en esta sección es más grande (incluye más valores, no solamente el 2.5% pero el 5% de los valores).</p>
<div class="sourceCode" id="cb430"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">randsup</span><span class="op">=</span><span class="fl">2.015</span></span>
<span><span class="va">d8</span> <span class="op">&lt;-</span> <span class="va">d5</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_area</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">db5</span>, <span class="va">x</span> <span class="op">&gt;</span> <span class="va">randsup</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"red"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="va">rlt_theme</span></span>
<span></span>
<span></span>
<span><span class="va">d7</span> <span class="op">&lt;-</span> <span class="va">d5</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_area</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">db5</span>, <span class="va">x</span> <span class="op">&lt;</span> <span class="op">-</span><span class="va">randsup</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"red"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="va">rlt_theme</span></span>
<span></span>
<span><span class="fu">gridExtra</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/gridExtra/man/arrangeGrob.html">grid.arrange</a></span><span class="op">(</span><span class="va">d7</span>,<span class="va">d8</span>, ncol<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="BioEstadistica_files/figure-html/c13-13-1.png" alt="" width="672"></div>
<hr>
</div>
<div id="el-intervalo-de-confianza-de-mu" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> El intervalo de confianza de <span class="math inline">\(\mu\)</span><a class="anchor" aria-label="anchor" href="#el-intervalo-de-confianza-de-mu"><i class="fas fa-link"></i></a>
</h2>
<p>Ahora se demuestra cómo calcular el intervalo de confianza de <span class="math inline">\(\mu\)</span>. Seleccionando un conjunto de datos al azar <strong>n</strong> se puede calcular el promedio <span class="math inline">\(\overline{x}\)</span> y el estimado de la desviación estándar <strong>s</strong>, con estos valores podemos calcular el rango donde pudiese estar el promedio del universo <span class="math inline">\(\mu\)</span> con cierto nivel de confianza (Tipo de Error I, <span class="math inline">\(\alpha\)</span>).</p>
</div>
<div id="ejemplo-9.3" class="section level2" number="13.6">
<h2>
<span class="header-section-number">13.6</span> Ejemplo 9.3<a class="anchor" aria-label="anchor" href="#ejemplo-9.3"><i class="fas fa-link"></i></a>
</h2>
<p>Se selecciona 20 peces machos de una misma especie en un riachuelo de Puerto Rico y se mide el largo en milímetros. El promedio es <span class="math inline">\(\overline{x}=21.0mm\)</span> y una desviación estándar <span class="math inline">\(s=1.76mm\)</span>. Queremos construir un intervalo de confianza de 95%. El tamaño de los peces es aproximadamente normal.</p>
<p>Queremos calcular el intervalo que incluye el 95%; por consiguiente, es el rango que hay en el área gris de la primera figura.</p>
<div class="definicion">
<p><strong>Intervalo de confianza (IC).</strong> Es un rango de valores, calculado a partir de una muestra, que con cierto nivel de confianza (por ejemplo, 95%) se espera que contenga el verdadero parámetro poblacional (<span class="math inline">\(\mu\)</span>). Un IC del 95% significa que, si repitiéramos el muestreo muchas veces, aproximadamente el 95% de los intervalos construidos contendrían el verdadero <span class="math inline">\(\mu\)</span>. NO significa que haya un 95% de probabilidad de que <span class="math inline">\(\mu\)</span> esté en un intervalo particular ya calculado.</p>
</div>
<hr>
</div>
<div id="los-limites-del-intervalo" class="section level2" number="13.7">
<h2>
<span class="header-section-number">13.7</span> Los limites del intervalo<a class="anchor" aria-label="anchor" href="#los-limites-del-intervalo"><i class="fas fa-link"></i></a>
</h2>
<p>Para calcular el intervalo se necesita solamente el valor de <em>t</em> con el tipo de error I del 5% (95% de confianza) que corresponde a un tamaño de muestra de 20, <span class="math inline">\(t_{0.05,\ n-1}\)</span>. Para conocer este valor hay que ir a una tabla de la distribución de t (vea p. 217 en el libro) o usar R para calcular el valor. En la tabla busca el error I deseado (0.05) y se busca el grado de libertad <em>n-1</em>, <span class="math inline">\(t_{0.05,\ 19}\)</span>. El valor del libro es <span class="math inline">\(t = 2.093\)</span>. Si se quisiera un tipo de error I de solamente 1%, el valor sería <span class="math inline">\(t=2.8609\)</span> (busca la información en la tabla o usa la función <strong>qt()</strong>).</p>
<div class="sourceCode" id="cb431"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">19</span><span class="op">)</span><span class="op">)</span> <span class="co"># nota que se usa la mitad de 0.05, por que es una prueba de dos lados. </span></span></code></pre></div>
<pre><code>## [1] 2.093024</code></pre>
<div class="sourceCode" id="cb433"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fl">21</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">19</span><span class="op">)</span><span class="op">*</span><span class="op">(</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 21.82371</code></pre>
<hr>
</div>
<div id="el-limite-superior" class="section level2" number="13.8">
<h2>
<span class="header-section-number">13.8</span> El limite superior<a class="anchor" aria-label="anchor" href="#el-limite-superior"><i class="fas fa-link"></i></a>
</h2>
<p>Ahora falta sustituir los valores en la fórmula</p>
<p><span class="math display">\[UL_{0.95}=\overline{x}+\left(t_{0.05,\ n-1}\cdot\frac{s}{\sqrt{n}}\right)\]</span></p>
<p><span class="math display">\[UL_{0.95}=21+2.093\cdot\left(\frac{1.76}{\sqrt{20}}\right)=21.824\]</span></p>
<hr>
</div>
<div id="el-limite-inferior" class="section level2" number="13.9">
<h2>
<span class="header-section-number">13.9</span> El limite inferior<a class="anchor" aria-label="anchor" href="#el-limite-inferior"><i class="fas fa-link"></i></a>
</h2>
<p><span class="math display">\[LL_{0.95}=\overline{x}-\left(t_{0.05,\ n-1}\cdot\frac{s}{\sqrt{n}}\right)\]</span></p>
<p><span class="math display">\[LL_{0.95}=21-2.093\cdot\left(\frac{1.76}{\sqrt{20}}\right)=20.176\]</span></p>
<hr>
<p>El intervalo de confianza de <span class="math inline">\(\mu\)</span> está entre 20.176 y 21.824 con un 95% de confianza.</p>
<div class="sourceCode" id="cb435"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">UL</span><span class="op">=</span><span class="fl">21</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">19</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">LL</span><span class="op">=</span><span class="fl">21</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">19</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">UL</span></span></code></pre></div>
<pre><code>## [1] 21.82371</code></pre>
<div class="sourceCode" id="cb437"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">LL</span></span></code></pre></div>
<pre><code>## [1] 20.17629</code></pre>
<hr>
</div>
<div id="menos-grados-de-libertad" class="section level2" number="13.10">
<h2>
<span class="header-section-number">13.10</span> Menos grados de libertad<a class="anchor" aria-label="anchor" href="#menos-grados-de-libertad"><i class="fas fa-link"></i></a>
</h2>
<p>Nota lo que pasa si uno tiene menos datos o más datos con el intervalo de confianza.</p>
<p>Con un tamaño de muestra de solamente 5 datos, el IC de 95% está entre 18.815 y 23.185. Por tener menos datos, el intervalo es más ancho: tenemos menos precisión sobre dónde se encuentra el promedio del universo.</p>
<div class="sourceCode" id="cb439"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">UL</span><span class="op">=</span><span class="fl">21</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">4</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">LL</span><span class="op">=</span><span class="fl">21</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">4</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">UL</span></span></code></pre></div>
<pre><code>## [1] 23.18533</code></pre>
<div class="sourceCode" id="cb441"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">LL</span></span></code></pre></div>
<pre><code>## [1] 18.81467</code></pre>
<hr>
</div>
<div id="más-grados-de-libertad" class="section level2" number="13.11">
<h2>
<span class="header-section-number">13.11</span> Más grados de libertad<a class="anchor" aria-label="anchor" href="#m%C3%A1s-grados-de-libertad"><i class="fas fa-link"></i></a>
</h2>
<p>Ahora con un tamaño de muestra de 100. El intervalo de confianza está más estrecho: 20.651 a 21.349.</p>
<div class="sourceCode" id="cb443"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">UL</span><span class="op">=</span><span class="fl">21</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">99</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">100</span><span class="op">)</span></span>
<span><span class="va">LL</span><span class="op">=</span><span class="fl">21</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">99</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">100</span><span class="op">)</span></span>
<span><span class="va">UL</span></span></code></pre></div>
<pre><code>## [1] 21.34922</code></pre>
<div class="sourceCode" id="cb445"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">LL</span></span></code></pre></div>
<pre><code>## [1] 20.65078</code></pre>
<hr>
</div>
<div id="muchos-muestreos-y-el-universo" class="section level2" number="13.12">
<h2>
<span class="header-section-number">13.12</span> Muchos muestreos y el universo<a class="anchor" aria-label="anchor" href="#muchos-muestreos-y-el-universo"><i class="fas fa-link"></i></a>
</h2>
<p>Para demostrar lo que quiere decir el intervalo de confianza evaluamos el siguiente gráfico. Cada linea horizontal representa un muestreo independiente, la pequeña linea vertical representa el promedio de este muestreo <span class="math inline">\(\overline{x}\)</span>, y la linea vertical que cruza todos los muestreos representa el promedio universal <span class="math inline">\(\mu\)</span>. Nota que en este caso el intervalo de confianza casi siempre cruza <span class="math inline">\(\mu\)</span>, aparte de uno. Ese muestreo, aunque proviene de la misma población, no incluyó el promedio del universo.</p>
<div class="figure">
<span style="display:block;" id="fig:c13-18"></span>
<img src="Havel_Figures/9-3%20Series%20-%20Confidence%20Interals.jpg" alt="Su promedio incluye el promedio del universo?" width="70%"><p class="caption">
Figure 13.1: Su promedio incluye el promedio del universo?
</p>
</div>
<hr>
<div id="quiz-estas-preguntas-la-tienen-que-contestar-en-una-asignación." class="section level3" number="13.12.1">
<h3>
<span class="header-section-number">13.12.1</span> QUIZ: estas preguntas la tienen que contestar en una asignación.<a class="anchor" aria-label="anchor" href="#quiz-estas-preguntas-la-tienen-que-contestar-en-una-asignaci%C3%B3n."><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>
<p>Titulo: Ultrasound evaluation of the morphometric patterns of lymph nodes of the head and neck in young and middle-aged individuals. Ogassavara et al. 2016, 49:225-228, Radiologia Brasileira. doi: 10.1590/0100-3984.2015.0002.</p>
<ul>
<li>En este trabajo evaluaron los ganglios linfáticos de 20 individuos sanos. Encontraron que la media de los ganglios linfáticos mastoideos de los hombres era de 0,9 cm con una desviación estándar de 0,4 cm.</li>
<li>¿Cuál es el intervalo de confianza al 95% de los ganglios linfáticos mastoideos en hombres? .</li>
</ul>
</li>
<li>
<p>Usando los mismo datos de la pregunta #1. Titulo: Ultrasound evaluation of the morphometric patterns of lymph nodes of the head and neck in young and middle-aged individuals. Ogassavara et al. 2016, 49:225-228, Radiologia Brasileira. doi: 10.1590/0100-3984.2015.0002.</p>
<ul>
<li>En este trabajo evaluaron los ganglios linfáticos de 20 individuos sanos. Encontraron que la media de los ganglios linfáticos mastoideos de los hombres era de 0,9 cm con una desviación estándar de 0,4 cm. Ya se pudo medir el tamaño de los ganglios linfáticos mastoideos de TODOS los hombres del planeta, y se determino que que el promedio es de 0.7 cm con una desviación estándar de 0,2 cm.</li>
<li>Usando los siguientes datos haga la prueba correspondiente en R para determinar el valor de t, observado y el valor critico.</li>
</ul>
</li>
</ol>
<div class="sourceCode" id="cb447"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">UL</span><span class="op">=</span><span class="fl">21</span><span class="op">+</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">4</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">LL</span><span class="op">=</span><span class="fl">21</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">4</span><span class="op">)</span><span class="op">*</span><span class="fl">1.76</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">UL</span></span></code></pre></div>
<pre><code>## [1] 23.18533</code></pre>
<div class="sourceCode" id="cb449"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">LL</span></span></code></pre></div>
<pre><code>## [1] 18.81467</code></pre>
<hr>
</div>
</div>
<div id="la-prueba-de-t-de-una-muestra" class="section level2" number="13.13">
<h2>
<span class="header-section-number">13.13</span> La prueba de t de una muestra<a class="anchor" aria-label="anchor" href="#la-prueba-de-t-de-una-muestra"><i class="fas fa-link"></i></a>
</h2>
<p>Esta prueba esencialmente calcula la media de los datos y construye un intervalo de confianza. Si el valor que estamos probando cae dentro de ese intervalo de confianza, concluimos que el valor del universo está incluido dentro del rango; de lo contrario, concluimos que no es la verdadera media. Nota que <span class="math inline">\(\mu\)</span> representa el modelo nulo, o sea la hipótesis nula. Si <span class="math inline">\(\mu=0\)</span> decimos que el universo es igual a cero.</p>
<p>Por ejemplo, evaluamos el promedio del nivel de colesterol en mujeres. Sabemos que las mujeres en el universo tienen un nivel de colesterol de <span class="math inline">\(\mu=209.4\)</span>, y ahora evaluamos un grupo de puertorriqueñas con un promedio de <span class="math inline">\(\overline{x}= 196.7\)</span> y una desviación estándar de <span class="math inline">\(s=39.1\)</span>, en un muestreo de 30.</p>
<p>¿Es la diferencia suficiente para decir que lo que se observó es significativamente diferente del universo a un nivel de error <span class="math inline">\(\alpha=0.05\)</span>? Lo que necesitamos hacer ahora es sustituir los valores en la fórmula. Observamos un valor de <em>t</em> observado de <span class="math inline">\(|t|=1.78\)</span>, y lo comparamos con el valor de <em>t</em> crítico <span class="math inline">\(=2.045\)</span> (para 29 grados de libertad, valor absoluto).</p>
<p>El resultado: el valor de <em>t</em> observado (1.78) es <strong>menor</strong> que el valor crítico (2.045) y, por consiguiente, <strong>no rechazamos</strong> la hipótesis nula. No hay evidencia suficiente para concluir que el nivel de colesterol de la muestra (<span class="math inline">\(\overline{x}= 196.7\)</span>) sea significativamente diferente del nivel universal (<span class="math inline">\(\mu=209.4\)</span>) a un nivel de <span class="math inline">\(\alpha=0.05\)</span>.</p>
<div class="interpretacion">
<p>Revisa el resultado de la próxima celda de código: R calcula <span class="math inline">\(|t|=1.78\)</span> y un <em>t</em> crítico de <span class="math inline">\(2.045\)</span>. Como el <em>t</em> observado no supera al crítico, <strong>no rechazamos</strong> la hipótesis nula. Recuerda: no rechazar Ho no prueba que <span class="math inline">\(\mu=209.4\)</span>; solo indica que no tenemos evidencia suficiente en contra.</p>
</div>
<ul>
<li>Ho: <span class="math inline">\(\overline{x}=\mu\)</span>
</li>
<li>Ha: <span class="math inline">\(\overline{x}≠\mu\)</span>
</li>
</ul>
<p><span class="math display">\[|t|=\frac{\left(\overline{x}-\mu_0\right)}{\frac{s}{\sqrt{n}}}\]</span>
Sustitución de los valores en la prueba de t.</p>
<div class="sourceCode" id="cb451"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="op">(</span><span class="fl">196.7</span><span class="op">-</span><span class="fl">209.4</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="op">(</span><span class="fl">39.1</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">30</span><span class="op">)</span><span class="op">)</span> <span class="op">)</span></span>
<span><span class="va">t</span> <span class="co"># Valor t de observado</span></span></code></pre></div>
<pre><code>## [1] 1.779048</code></pre>
<div class="sourceCode" id="cb453"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">29</span><span class="op">)</span><span class="op">)</span>  <span class="co"># valor de t-critico, de la tabla</span></span></code></pre></div>
<pre><code>## [1] 2.04523</code></pre>
<p>Para enterder mejor como cambia el valor de t critico con el tamaño de muestra vea la siguiente tabla. <a href="https://numiqo.com/tutorial/t-distribution" class="uri">https://numiqo.com/tutorial/t-distribution</a></p>
<hr>
</div>
<div id="propinas" class="section level2" number="13.14">
<h2>
<span class="header-section-number">13.14</span> Propinas<a class="anchor" aria-label="anchor" href="#propinas"><i class="fas fa-link"></i></a>
</h2>
<p>Un ejemplo con datos en una tabla
Usamos un conjunto de datos en el paquete <strong>reshape</strong>, que llama <strong>tips</strong>. Se refiere a las propinas que reciben los meseros.</p>
<p>Nuestra hipótesis es que en promedio, las personas dan una propina de $2.50, Esta es nuestra hipótesis <strong>nula</strong></p>
<p>Nuestra hipótesis <strong>alternativa</strong> es que las personas dan significativamente más o menos de $2.50.</p>
<ul>
<li>Ho: <span class="math inline">\(\overline{x}=\mu\)</span>
</li>
<li>Ha: <span class="math inline">\(\overline{x}≠\mu\)</span>
</li>
</ul>
<pre><code>##   total_bill  tip    sex smoker day   time size
## 1      16.99 1.01 Female     No Sun Dinner    2
## 2      10.34 1.66   Male     No Sun Dinner    3
## 3      21.01 3.50   Male     No Sun Dinner    3
## 4      23.68 3.31   Male     No Sun Dinner    2
## 5      24.59 3.61 Female     No Sun Dinner    4
## 6      25.29 4.71   Male     No Sun Dinner    4</code></pre>
<hr>
<p>Con la función <strong>t.test()</strong> es muy sencillo hacer la prueba; no hay que calcular a mano, solamente hay que añadir la información.</p>
<p>Las opciones para esta prueba son las siguientes (en rojo)</p>
<ul>
<li>t.test(<span style="color: red;">x</span>, y = NULL,
<ul>
<li>
<span style="color: red;">alternative = c(two.sided, less, greater)</span>,</li>
<li>
<span style="color: red;">mu = 0</span>, paired = FALSE, var.equal = FALSE,</li>
<li>
<span style="color: red;">conf.level = 0.95</span>, …).</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb456"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">tipTTest</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">tip</span>, alternative <span class="op">=</span> <span class="st">"two.sided"</span>, mu<span class="op">=</span><span class="fl">2.50</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tipTTest</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  tips$tip
## t = 5.6253, df = 243, p-value = 5.08e-08
## alternative hypothesis: true mean is not equal to 2.5
## 95 percent confidence interval:
##  2.823799 3.172758
## sample estimates:
## mean of x 
##  2.998279</code></pre>
<p>El resultado: el valor de <em>t</em> observado es de 5.625, con 243 grados de libertad (n=244) y un valor de <em>p</em> &lt; 0.0001. Por consiguiente, se rechaza la hipótesis nula. El intervalo de confianza del promedio es $2.82 – $3.17, con un promedio de $3.00.</p>
<hr>
</div>
<div id="cómo-graficar-el-resultado-de-una-prueba-t" class="section level2" number="13.15">
<h2>
<span class="header-section-number">13.15</span> ¿Cómo graficar el resultado de una prueba t?<a class="anchor" aria-label="anchor" href="#c%C3%B3mo-graficar-el-resultado-de-una-prueba-t"><i class="fas fa-link"></i></a>
</h2>
<p>Pasos</p>
<blockquote>
<ul>
<li>Crear una distribución normal de la hipótesis <strong>NULA</strong> con un promedio igual al valor propuesto por la hipótesis nula (<span class="math inline">\(\mu\)</span>)</li>
<li>Calcule las estadísticas t.test</li>
<li>Dibuje la media de la estadística t en la figura
<ul>
<li>la linea entrecortada representa el intervalo de confianza de 95%</li>
<li>la linea roja representa la estadística de los datos.</li>
</ul>
</li>
</ul>
</blockquote>
<p>En este ejemplo observamos que el promedio estimado está por encima del intervalo de confianza (las líneas entrecortadas).</p>
<div class="sourceCode" id="cb458"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># The calculated t-statistic</span></span>
<span><span class="va">t_calculated</span> <span class="op">&lt;-</span> <span class="va">tipTTest</span><span class="op">$</span><span class="va">statistic</span></span>
<span></span>
<span><span class="co"># The degrees of freedom</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">tipTTest</span><span class="op">$</span><span class="va">parameter</span></span>
<span></span>
<span><span class="co"># The critical t-values for a two-sided 95% test</span></span>
<span><span class="va">t_critical_upper</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.975</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">t_critical_lower</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.025</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create a sequence of t-values for the density curve</span></span>
<span><span class="va">t_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, length.out <span class="op">=</span> <span class="fl">500</span><span class="op">)</span></span>
<span><span class="va">t_distribution</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>t <span class="op">=</span> <span class="va">t_values</span>, density <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">dt</a></span><span class="op">(</span><span class="va">t_values</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">t_distribution</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">t</span>, y <span class="op">=</span> <span class="va">density</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Plot the theoretical t-distribution</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"grey"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_area</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey"</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Plot the Critical t-values (defining the rejection regions)</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">t_critical_lower</span>, <span class="va">t_critical_upper</span><span class="op">)</span>, </span>
<span>             linetype <span class="op">=</span> <span class="st">"dashed"</span>, color <span class="op">=</span> <span class="st">"black"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Plot the Calculated t-statistic from the test</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">t_calculated</span>, colour <span class="op">=</span> <span class="st">"red"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Add labels</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"t-statistic Value"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Density"</span>,</span>
<span>    title <span class="op">=</span> <span class="st">"Calculated t-statistic vs. t-Distribution"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="BioEstadistica_files/figure-html/c13-25-1.png" alt="" width="672"></div>
<hr>
</div>
<div id="ejercicio-de-práctica-1-amigos-de-facebook" class="section level2" number="13.16">
<h2>
<span class="header-section-number">13.16</span> Ejercicio de práctica 1: Amigos de Facebook<a class="anchor" aria-label="anchor" href="#ejercicio-de-pr%C3%A1ctica-1-amigos-de-facebook"><i class="fas fa-link"></i></a>
</h2>
<p>Mucha gente cree que la cantidad promedio de amigos en Facebook es 338, con una desviación estándar de 43.2. En un muestreo al azar de 50 estudiantes universitarios en un país se calculó que el promedio de estos estudiantes es de 350 amigos. A un nivel de 5% de error, determina si hay evidencia de que los estudiantes tengan mayor número de amigos que el promedio anunciado por Facebook.</p>
<div class="sourceCode" id="cb459"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="va">FB_friends</span><span class="op">=</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">amigos</span>,</span>
<span> <span class="fl">3000</span>, <span class="fl">3100</span>, <span class="fl">1348</span>, <span class="fl">5000</span>, <span class="fl">620</span>, <span class="fl">400</span>, <span class="fl">300</span>, <span class="fl">10</span>, <span class="fl">1500</span>, <span class="fl">400</span>,</span>
<span>  <span class="fl">600</span>, <span class="fl">700</span>, <span class="fl">800</span>, <span class="fl">900</span>, <span class="fl">1000</span>, <span class="fl">1100</span>, <span class="fl">1200</span>, <span class="fl">1300</span>, <span class="fl">1400</span>, <span class="fl">1500</span><span class="op">)</span></span>
<span></span>
<span><span class="va">FB_friends</span></span></code></pre></div>
<pre><code>## # A tibble: 20 × 1
##    amigos
##     &lt;dbl&gt;
##  1   3000
##  2   3100
##  3   1348
##  4   5000
##  5    620
##  6    400
##  7    300
##  8     10
##  9   1500
## 10    400
## 11    600
## 12    700
## 13    800
## 14    900
## 15   1000
## 16   1100
## 17   1200
## 18   1300
## 19   1400
## 20   1500</code></pre>
<div class="sourceCode" id="cb461"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">FB_friends</span><span class="op">$</span><span class="va">amigos</span>, alternative<span class="op">=</span><span class="st">"two.sided"</span>, mu<span class="op">=</span><span class="fl">350</span>, conf.level <span class="op">=</span> <span class="fl">.95</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  FB_friends$amigos
## t = 3.6619, df = 19, p-value = 0.001658
## alternative hypothesis: true mean is not equal to 350
## 95 percent confidence interval:
##   760.8168 1856.9832
## sample estimates:
## mean of x 
##    1308.9</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><p>Cual es valor de t</p></li>
<li><p>Cual es el valor de t critico</p></li>
<li><p>¿Se rechaza o acepta la hipótesis nula?</p></li>
</ol>
<hr>
</div>
<div id="ejercicio-de-práctica-2-dias-de-enfermedades" class="section level2" number="13.17">
<h2>
<span class="header-section-number">13.17</span> Ejercicio de práctica 2: Dias de enfermedades<a class="anchor" aria-label="anchor" href="#ejercicio-de-pr%C3%A1ctica-2-dias-de-enfermedades"><i class="fas fa-link"></i></a>
</h2>
<p>El dueño de una empresa insiste en que la cantidad promedio de días de enfermedad de sus empleados es menor que el promedio nacional de 10. Los datos de 40 empleados siguen a continuación. Determina si hay evidencia para creer el comentario del dueño de esta empresa.</p>
<div class="sourceCode" id="cb463"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dias_E</span><span class="op">=</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">Enfermedad</span>,</span>
<span>  <span class="fl">0</span>,<span class="fl">6</span>,<span class="fl">12</span>,<span class="fl">3</span>,<span class="fl">3</span>,<span class="fl">5</span>,<span class="fl">4</span>,<span class="fl">1</span>,</span>
<span>  <span class="fl">3</span>,<span class="fl">9</span>,<span class="fl">6</span>,<span class="fl">0</span>,<span class="fl">7</span>,<span class="fl">6</span>,<span class="fl">3</span>,<span class="fl">4</span>,</span>
<span>  <span class="fl">7</span>,<span class="fl">4</span>,<span class="fl">7</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">8</span>,<span class="fl">12</span>,<span class="fl">3</span>,</span>
<span>  <span class="fl">2</span>,<span class="fl">5</span>,<span class="fl">10</span>,<span class="fl">5</span>,<span class="fl">15</span>,<span class="fl">3</span>,<span class="fl">2</span>,<span class="fl">5</span>,</span>
<span>  <span class="fl">3</span>,<span class="fl">11</span>,<span class="fl">8</span>,<span class="fl">2</span>,<span class="fl">2</span>,<span class="fl">4</span>,<span class="fl">1</span>,<span class="fl">9</span></span>
<span><span class="op">)</span></span>
<span><span class="va">dias_E</span></span></code></pre></div>
<pre><code>## # A tibble: 40 × 1
##    Enfermedad
##         &lt;dbl&gt;
##  1          0
##  2          6
##  3         12
##  4          3
##  5          3
##  6          5
##  7          4
##  8          1
##  9          3
## 10          9
## # ℹ 30 more rows</code></pre>
</div>
<div id="supuesto" class="section level2" number="13.18">
<h2>
<span class="header-section-number">13.18</span> <strong>Supuesto</strong><a class="anchor" aria-label="anchor" href="#supuesto"><i class="fas fa-link"></i></a>
</h2>
<div class="supuestos">
<p>El supuesto principal de la prueba de <em>t</em> de una muestra es que los datos son aproximadamente normales (o que el tamaño de muestra es suficientemente grande). Este supuesto se puede evaluar con un histograma o una gráfica Q-Q. La prueba también asume que las observaciones son independientes.</p>
</div>
<p>En este caso los datos parecen ser aproximadamente normales.</p>
<p>En otras palabras, no se puede usar esta prueba si los datos no son aproximadamente normales, por ejemplo si tienen una distribución de Poisson (conteos) o si son categóricos.</p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="distribuci%C3%B3n-normal.html"><span class="header-section-number">12</span> Distribución Normal</a></div>
<div class="next"><a href="prueba-de-t-para-datos-pareados.html"><span class="header-section-number">14</span> Prueba de t para Datos Pareados</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#prueba-de-una-muestra"><span class="header-section-number">13</span> Prueba de una Muestra</a></li>
<li><a class="nav-link" href="#el-promedio-un-estimado"><span class="header-section-number">13.1</span> El promedio, un estimado</a></li>
<li><a class="nav-link" href="#ejemplo-9.1-y-9.2."><span class="header-section-number">13.2</span> Ejemplo 9.1 y 9.2.</a></li>
<li><a class="nav-link" href="#la-distribuci%C3%B3n-de-t"><span class="header-section-number">13.3</span> La distribución de t</a></li>
<li><a class="nav-link" href="#cuando-es-que-uno-rechaza-la-hip%C3%B3tesis-nula"><span class="header-section-number">13.4</span> Cuando es que uno rechaza la hipótesis nula</a></li>
<li><a class="nav-link" href="#el-intervalo-de-confianza-de-mu"><span class="header-section-number">13.5</span> El intervalo de confianza de \(\mu\)</a></li>
<li><a class="nav-link" href="#ejemplo-9.3"><span class="header-section-number">13.6</span> Ejemplo 9.3</a></li>
<li><a class="nav-link" href="#los-limites-del-intervalo"><span class="header-section-number">13.7</span> Los limites del intervalo</a></li>
<li><a class="nav-link" href="#el-limite-superior"><span class="header-section-number">13.8</span> El limite superior</a></li>
<li><a class="nav-link" href="#el-limite-inferior"><span class="header-section-number">13.9</span> El limite inferior</a></li>
<li><a class="nav-link" href="#menos-grados-de-libertad"><span class="header-section-number">13.10</span> Menos grados de libertad</a></li>
<li><a class="nav-link" href="#m%C3%A1s-grados-de-libertad"><span class="header-section-number">13.11</span> Más grados de libertad</a></li>
<li>
<a class="nav-link" href="#muchos-muestreos-y-el-universo"><span class="header-section-number">13.12</span> Muchos muestreos y el universo</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#quiz-estas-preguntas-la-tienen-que-contestar-en-una-asignaci%C3%B3n."><span class="header-section-number">13.12.1</span> QUIZ: estas preguntas la tienen que contestar en una asignación.</a></li></ul>
</li>
<li><a class="nav-link" href="#la-prueba-de-t-de-una-muestra"><span class="header-section-number">13.13</span> La prueba de t de una muestra</a></li>
<li><a class="nav-link" href="#propinas"><span class="header-section-number">13.14</span> Propinas</a></li>
<li><a class="nav-link" href="#c%C3%B3mo-graficar-el-resultado-de-una-prueba-t"><span class="header-section-number">13.15</span> ¿Cómo graficar el resultado de una prueba t?</a></li>
<li><a class="nav-link" href="#ejercicio-de-pr%C3%A1ctica-1-amigos-de-facebook"><span class="header-section-number">13.16</span> Ejercicio de práctica 1: Amigos de Facebook</a></li>
<li><a class="nav-link" href="#ejercicio-de-pr%C3%A1ctica-2-dias-de-enfermedades"><span class="header-section-number">13.17</span> Ejercicio de práctica 2: Dias de enfermedades</a></li>
<li><a class="nav-link" href="#supuesto"><span class="header-section-number">13.18</span> Supuesto</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/RaymondLTremblay/BioEstadistica/blob/master/13-Prueba_de_una_muestra.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/RaymondLTremblay/BioEstadistica/edit/master/13-Prueba_de_una_muestra.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>BioEstadística</strong>" was written by . It was last built on 2026-08-01.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
